name: Publish Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Prepare build environment
        run: make prepare

      - name: Build docs
        run: make pages

      - name: Publish docs
        run: |
          git config --global user.name 'LabML Build Bot'
          git config --global user.email 'buildbot@labml.ai'
          git add html
          git commit -am "Publishing Docs"
          git push
